"""
Django settings for bookstore project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import os



env=environ.Env(DEBUG=(bool,False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Read .env file
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("SECRET_KEY")



SECRET_KEY = 'django-insecure-9i1d@b_zr13xmbnr=490n&f6ktz(%atj8epchex8og5e4i_!!y'
DEBUG=True
SIGNING_KEY="BWrz80LirzsZTvRSjHKJRljSK2mCOJmg"


ALLOWED_HOSTS = []

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",  # Add your allowed origins here
    "http://localhost:3000",  # For local development
    "http://localhost:8000"
]

# settings.py

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    #  'admin_soft.apps.AdminSoftDashboardConfig',
    #  'users.apps.SuitConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #external apps
    'rest_framework',
    'corsheaders',
    'djoser',
    "rest_framework_simplejwt",
    'crispy_forms',

    #inernal apps
    'users',
    'store',
     'cart',
    'order',
    'wishlist',



    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Should be placed before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
   'ENGINE': 'django.db.backends.postgresql',
        'HOST': 'localhost',
        'NAME': 'book',
        'USER': 'postgres',
        'PASSWORD': '111',
        'PORT': 5432    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# STATIC_URL = 'static/'
# STATICFILES_DIRS=['static']
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/')
]

#Media files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')



AUTH_USER_MODEL='users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": (
        "Bearer",
        "JWT"),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=360),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    "SIGNING_KEY": "BWrz80LirzsZTvRSjHKJRljSK2mCOJmg",
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


DJOSER = {
    'LOGIN_FIELD': 'email',
    "USER_CREATE_PASSWORD_RETYPE": True,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
     "SEND_CONFIRMATION_EMAIL": True,
    "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}",
    "SET_PASSWORD_RETYPE": True,
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SERIALIZERS': {
        'user_create': 'users.serializers.CreateUserSerializer',
        'user': "users.serializers.CreateUserSerializer",
        'user_delete': "djoser.serializers.UserDeleteSerializer",      
    },



}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "enasmetwally99@gmail.com"
# EMAIL_HOST_PASSWORD = "m p s h s x d a j v w f p d e x"
EMAIL_HOST_PASSWORD = "codl bijc stcb baav"

DEFAULT_FROM_EMAIL = "enasmetwally@gmail.com"
SITE_NAME = "book"
DOMAIN="localhost:3000"




#paypal
# settings.py

# PAYPAL_CLIENT_ID = 'AfWqLOp1dZXQ2Js_hzGvDC5Gu1M__SyHw_C0ga2bisLiGojxos2e6AUKafuQapsZ0BmpsgGHYoSCoK5D'
# PAYPAL_SECRET = 'ENi5r_3eGNiBgI4P7CI_6KuwkjyRG3yei2ZkiL4M95iGT7CfEgX070jKIvM7ErQ_Adbb2WaFkRTYzI2H'


PAYPAL_CLIENT_ID = 'ATqO0oF7-MYpieuj1IgPdtXYS4d47J2r8ddyyDO3Uvea8Z1OSiKKCRQwBW2-iOq2IEu_HGtatxpjR6ze'
PAYPAL_SECRET = 'EItU7MN9cr9-oIuiLJpHIVbNNZPDpX8W4RVovSKmKNAWqZCbSCI5Id_ARagh-1ChTamVQXvWcXdnf0Mv'